spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  

server:
  port: 8080

logging:
  file:
    name: log/blog-dev/blog.log
  level:
    root: info
    '[com.newyearblog]': debug
